"""
Euler 29
Consider all integer combinations of a**b for 2 <= a <= 5 and 2 <= b <= 5:
How many distinct terms are in the sequence generated by a**b for 2 <= a <= 100 and 2 <= b <= 100?

Solution: 9183
Runs in 0.0468 secs
"""
sequence_range = range(2, 101)

answer_set = set([])

for a in sequence_range:
    for b in sequence_range:
        answer_set.add(a ** b)
print (len(list(answer_set)))
